#!/bin/bash
echo "enter first number:"
read a
echo "enter second number"
read b
echo "select choice:"
echo "1.Addition"
echo "2.Substraction"
echo "3.Multiplication"
echo "4.Division"
echo "choice"
read ch
if [ $ch == 1 ]
then
        sum=`expr $a + $b `
        echo "sum is :" $sum
elif [ $ch == 2 ]
then
        dfrnc=`expr $a - $b`
        echo "Difference is :" $dfrnc
elif [ $ch == 3 ]
then
